title: Saad Bouhya
#logo: /assets/img/headshot_circle.png
description: Soon to be a graduate of Centrale Lille and passionate about artificial intelligence, I have gained experience with several international groups such as Adeo and Stellantis. I am currently seeking a position as a data scientist or machine learning engineer in the Île-de-France region for September 2024.
show_downloads: false
theme: jekyll-theme-minimal
