title: Saad Bouhya
#logo: /assets/img/headshot_circle.png
description: Soon to be Centrale Lille graduate looking for a full time job as a Data Scientist  ML Engineer
show_downloads: false
theme: jekyll-theme-minimal
